### ISSUE TITLE
Initialize/Configure zeebe programmatically

### ISSUE THREAD

**Issue by AnuvadiyaHiren** [camunda-community-hub/spring-zeebe#148]
Developing proejct where we've requirement to retrive the zeebe configurations from user using UI and use this value to initialize

**Comment by berndruecker** [comment]
Hi @AnuvadiyaHiren - you could currently do this by creating the Java client yourself programmatically. I don#t think it is super easy to add this - especially as the ZeebeClient is initialized pretty early in the lifecycle. 

But if you have a good idea for doing this, you could probably work on a PR? Otherwise I would close this issue for now.
