### ISSUE TITLE
Feature Request: Inject variables typed in Handler Function

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/spring-zeebe#159]
This feature should enable the possibility to get variables injected in a typed manner like this:

```java
@ZeebeWorker(type = "foo", autoComplete = true)
public ProcessVariables handleFoo(@ZeebeTypedVariables ProcessVariables variables){
  // do whatever you need to do
  return variables;
}
```

Inspired by @berndruecker .

**Comment by berndruecker** [comment]
Hey @jonathanlukas: thanks for the proposal! I generally like it and think it allows some good ways to write workers. It would even allow writing a "CustomForThisJobVariable" class, as the client ignores all properties that cannot be deserialized. 

I am still thinking about the name, as I don't yet like @ZeebeTypesVariables too much, but also don't have a better idea just yet (and we could still adjust this after merging).

Quick question: Did you validate that it works if you change data in that variable object, return it and it is set as process variables?

And I just saw that you mixed in the possibility to set the name in @ZeebeVariable - we explicitly decided against that for the moment to avoid any confusion between how the variable in Java and the process variable are named. I don't yet see any good reason for them to differ - do you? Otherwise please remove this change from the PR.

Thanks again for taking the time and initiative :-)

**Comment by jonathanlukas** [comment]
Hi @berndruecker , thank you for your review. 

The name of the annotation also bothered me, as it is very long, but I had no better idea so I sticked to the naming of the API method.

To be open: I did not validate this, yet it actually does the same as:

```java
  @Override
  public void handle(JobClient client, ActivatedJob job) throws Exception {
    HandlerVariables variables = job.getVariablesAsType(HandlerVariables.class);
    // do what you will with this object
    client.newCompleteCommand(job.getKey()).variables(variables).send();
  }
```

And this works.

For the name of the @ZeebeVariable: I had the idea of introducing this as I am a friend of having variable names as psf String somewhere, like a dictionary, to prevent typos. This would not work when only using the variable name as "mapper".

If this is an uncommon use case, I can remove it again.

On the other hand, this feature is a bit "hidden". If you fear that this leaves a developer in confusion, I would add a comment on the value field in the annotation, explaining the use case.

I will again think of a better name for the annotation @ZeebeTypedVariables and modify the PR if I find a better one.

**Comment by berndruecker** [comment]
Fair point regarding the variables handling - I agree that this should work (I still want to add more testing with the testing library now out anyway :-)).

With the @ZeebeVariabnle(name) let's wait for enough pull from the community/users. Once introduced it is not easy to get rid of it, and I am sill not convinced we really need it (and then I am in favor of keeping it lean). Could you update the PR?
I think it is good practice to separate different things in different PR's anyway :-)

Thx!

**Comment by berndruecker** [comment]
Thinking about the annotation name a bit and I think I would go with 

`@ZeebeVariablesAsType`

which is completely in line with the method name (I agree on the avoiding confusion argument). I also think it works from a user perspective, I find it clearer in what it does:

`
  @ZeebeWorker(type = "test1", autoComplete = true)
  public void handleTest1(@ZeebeVariablesAsType MyProcessVariables variables) {
    variables.getMagicNumber();
  }
`

WDYT?

**Comment by jonathanlukas** [comment]
This look good - I will adjust the PR, removing the changes to @ZeebeVariable and renaming the other Annotation as well.

**Comment by jonathanlukas** [comment]
@berndruecker PR is adjusted, ready for your final review.

**Comment by berndruecker** [comment]
Thanks a lot! Actually, while washing the dishes I had one other thought: What if we treat all method parameters, that are 
- not annotated by @ZeebeVariable
- not the ActivatedJob
- not the JobClient
automatically as "VariablesAsType"?

Then we would not even need a marker annotation.

Pro: Shorter and easier for the user
Con: Might lead to issues if we want to add additional parameters, as they always then must have a marker annotation or specific type.

At the moment I can't think of any more parameters we want in the worker - so?

@falko - maybe you have an opinion on this?

**Comment by falko** [comment]
I'd love to avoid the `@ZeebeVariable` annotation in favor of a crisp readable syntax, especially when working with many variables. What confuses me is when you say to treat "all method parameters" as "VariablesAsType" because `job.getVariablesAsType(ProcessVariables.class);` maps all process variables to fields/properties of the provided class. So it wouldn't make sense to have multiple such objects. Unless, each of them is only a partial mapping, which I'm wondering how this is handled by the mapper.

Thus, my suggestion would be to use an `@VariablesAsType` annotation for the variables to object mapper and rather make `@ZeebeVariable` optional to say that all method parameters that are

- not annotated by `@ZeebeVariable`
- not the `ActivatedJob`
- not the `JobClient`
- not annotated with `@VariablesAsType`

will be treated as individual variables to be casted to the respective parameter type, e.g.

```java
@ZeebeWorker(type = "shipOrder", autoComplete = true)
public void shipOrder(String orderId, Boolean isGift) {
  // ship the package; wrap as gift if needed ;-)
}
```

The object mapper would thus stick to an annotation, which is less clutter in this case because it's only one such parameter:

```java
@ZeebeWorker(type = "shipOrder", autoComplete = true)
public ProcessVariables shipOrder(@ZeebeTypedVariables ProcessVariables variables){
  // do whatever you need to do
  return variables;
}
```

How do we know that the returned object must be mapped back to variables?

**Comment by berndruecker** [comment]
Thanks Falko - super helpful!

"So it wouldn't make sense to have multiple such objects. Unless, each of them is only a partial mapping, which I'm wondering how this is handled by the mapper." --> precisely, the mapper ignores everything that is not part of the variables class, so you could create classes containing partial mappings (not sure if this is a good idea though).

Let's do this: I'll merge the PR now and we will have the two annotations available. And then we wait a couple of months to see it used in reality, and then we can still define a shortcut to save annotations if we feel this is important. The other way round it would also mean to have a breaking chance - which we should not do.
