### ISSUE TITLE
[Testing] Solve problems because of Spring Tests running multi-threaded

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#162]
With the current setup, workers run in a separate thread, even if started up within a test case, as they are constructed normally. 

The multi-thread setup leads to issues when asserting state or waiting for idle, like:

1. Wired issues with the InMemoryEngine of Zeebe: https://github.com/camunda-cloud/zeebe-process-test/issues/110
2. `WaitForIdle` method on the InMemoryEngine does not work, as the workers are independent, leading to workaround like: https://github.com/berndruecker/camunda-cloud-zeebe-tests-playgorund/blob/main/src/test/java/io/berndruecker/playground/zeebe/tests/SimpleSpringBootTest.java#L75
```
 public void waitForCompletion(ProcessInstanceEvent processInstance) {
        Awaitility.await().atMost(Duration.ofMillis(1000)).untilAsserted(() -> {
            RecordStreamSourceStore.init(engine.getRecordStream());
            assertThat(processInstance).isCompleted();
            Thread.sleep(500L); // required to avoid https://github.com/camunda-cloud/zeebe-process-test/issues/110
        });
    }
```

This needs to be solved differently.

Still, my goal would be to allow workers to use the @ZeebeWorker annotation normally.

**Comment by pihme** [comment]
What do you mean by "workers"? I feel we are missing part of the picture here.

**Comment by berndruecker** [comment]
Hey @pihme: I actually wasn't even thinking about that you look into that - so that's why I kept it cryptic so that I (and maybe @zambrovski or @jangalinski) can understand :-)

But the short version is: In the spring environment I envision to run the normal worker code, but then inject mocks or fakes into those (to not do real service calls). I still need to write a realistic example (like [XX ](https://github.com/berndruecker/camunda-spring-boot-amqp-microservice-cloud-example/blob/master/src/test/java/com/camunda/demo/springboot/OrderProcessTest.java) for Camunda Platform), but a bit like this: https://github.com/berndruecker/camunda-cloud-zeebe-tests-playgorund/blob/main/src/test/java/io/berndruecker/playground/zeebe/tests/SimpleSpringBootTest.java#L68

**Comment by pihme** [comment]
Thanks @berndruecker for the example and explanation. I guess what I am trying to understand is why you want to inject mocks vs. something like: 

```java
      final ActivateJobsResponse jobActivationResponse =
          client
              .newActivateJobsCommand()
              .jobType(ProcessPackLoopingServiceTask.JOB_TYPE)
              .maxJobsToActivate(1)
              .send()
              .join();
      
      final ActivatedJob actual = jobActivationResponse.getJobs().get(0);
      
      client.newCompleteCommand(actual.getKey()).send().join();
```

Which gives you precise control over job execution, results and success or failure of individual calls.

This is relevant for us, because you are using the library different to assumptions I had. 
So thank you for that, because this is always interesting to learn!

Like in my head, I was thinking:
* Ok, if I want to test a worker, I will use https://github.com/camunda-community-hub/zeebe-worker-java-testutils and I can test them without a process engine
* And if I want to test the process, I use https://github.com/camunda-cloud/zeebe-process-test and I can test the process without any worker

And because of that mindset, there is no assertion in Zeebe process test like: `assertThat(job).completed().withVariables(variables`. I felt it wasn't needed, because simulating the worker is part of my test setup when I test the process.

And now I learn from you that you want to run mocked workers. Or maybe you want to at least enable users to test processes and workers in one go?

I am interested to learn more about how you will use the library for testing. In particular, once you feel like you have a good grip on "this is how I want to write my tests" I suggest we look again if anything is missing in the library to help you achieve that.

/cc @remcowesterhoud

**Comment by berndruecker** [comment]
Hi @pihme! Let me give you a quick gist here - but also happy to hop on a Zoom call to discuss!

I want to write a test case, that tests all process-related artifacts, which for me is the process model, and all glue code around it. If you look at https://github.com/berndruecker/camunda-cloud-zeebe-tests-playgorund/blob/main/src/test/java/io/berndruecker/playground/zeebe/tests/SimpleSpringBootTest.java you can see, that this simple uses the process model and then I could make assumptions on the side effects. In this case, I would just mock the REST-Client injected in https://github.com/berndruecker/camunda-cloud-zeebe-tests-playgorund/blob/main/src/main/java/io/berndruecker/playground/zeebe/tests/ServiceTaskAGlueCode.java#L16.

This is inline to how many customers write test cases with Camunda Platform, see https://github.com/berndruecker/camunda-spring-boot-amqp-microservice-cloud-example/blob/master/src/test/java/com/camunda/demo/springboot/OrderProcessTest.java#L103 as an example. There you test all surrounding glue code together with the process model - this gives you a good confidence that your process solution works. This is also described as "Scope 1" in https://camunda.com/best-practices/testing-process-definitions/# (just that so far I struggled to switch to single-threaded workers in spring-zeebe, which is kind of this issue).

Testing the adapters would be nice, but I don't see many people doing this in isolation. Same for the process model. I find the sketched scope the most pragmatic approach to test all important aspects in one go - and thus I find it most likely that people are really doing it.
