### ISSUE TITLE
Starting workers for OutboundConnector's 

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#230]
If an outbound connector is available

```
@OutboundConnector(
        name = "Twitter",
        inputVariables = {"tweetContent"},
        type = "io.berndruecker.example.TwitterConnector:1"
)
public class TwitterOutboundConnector implements OutboundConnectorFunction {
```

And this connector is made available as Spring bean
```
@Configuration
public class ConnectorFactory {
    @Bean
    public TwitterOutboundConnector twitterOutboundConnector() {
        return new TwitterOutboundConnector();
    }
}
```

Then a worker for this connector will be started

**Comment by namero999** [comment]
Thanks, we just hit this during the hack day :)

**Comment by berndruecker** [comment]
Just released a 8.0.10 containing it: https://github.com/camunda-community-hub/spring-zeebe/releases/tag/8.0.10

**Comment by berndruecker** [comment]
I reopen this issue to not forget to add something in the readme

**Comment by namero999** [comment]
Upgrading to 8.0.10 messes up logs a bit, especially with spring + log4j2.

Gotta be something with transitive dependencies, the connector sdk pulls in a bunch and I wonder if this is something that should be enforced or left optional. Will probably stay on .9 for now.

**Comment by berndruecker** [comment]
Hi @namero999 - thanks for the quick feedback! I actually checked transitive dependencies and don't find any that should make problems - did you investigate further and can point your finger to the root problem? Happy to resolve it quickly and release a .11!

![grafik](https://user-images.githubusercontent.com/1217596/194865148-9946c86e-4dd9-4818-a465-78af5235b8e9.png)

**Comment by namero999** [comment]
I believe the issue is that `io.camunda.connector:connector-runtime-job-worker` ships its own `log4j2.xml` at root context path.


<img width="1363" alt="Screenshot 2022-10-10 at 14 43 57" src="https://user-images.githubusercontent.com/1874223/194869757-76219a9f-32ea-4113-8b58-80013e5beaee.png">


Compare for instance the output with .9  vs .10


<img width="1792" alt="Screenshot 2022-10-10 at 14 36 29" src="https://user-images.githubusercontent.com/1874223/194869821-e18b2eea-74de-42b5-9ac0-514cc7ff37aa.png">

<img width="1792" alt="Screenshot 2022-10-10 at 14 43 18" src="https://user-images.githubusercontent.com/1874223/194869850-6604a089-b094-4869-80ed-018453428e9c.png">


There would be nothing wrong per se, but since this creates an unexpected change of the _default_ behaviour, it would be probably better to exclude the log4j config from the distribution.

**Comment by berndruecker** [comment]
I totally agree - this log config should not be on the classpath. I currently discuss how to generally deal with the connector-job-runtime as part of https://github.com/camunda/connector-sdk/pull/136#issuecomment-1273344893 - expect a fix soon-ish (and best wait for .11).

**Comment by berndruecker** [comment]
--> https://github.com/camunda-community-hub/spring-zeebe/commit/553fbc4f0debd4f13def4987b4e1afb2f2f00b79. 

Releasing 8.0.11 now: https://github.com/camunda-community-hub/spring-zeebe/releases/tag/8.0.11

**Comment by namero999** [comment]
Appreciated the fast reaction :)

**Comment by berndruecker** [comment]
It is on Maven Central now - maybe you (@namero999 ) could test 8.0.11 whenever convenient?
