### ISSUE TITLE
Lifecycle events in tests

### ISSUE THREAD

**Issue by stephanpelikan** [camunda-community-hub/spring-zeebe#320]
Hi,

I created a bean which is using the client based on the lifecycle events:

```java
    @Autowired
    private final ZeebeClientLifecycle clientLifecycle;
    private ZeebeClient client;
    @EventListener
    public void zeebeClientStarted(final ClientStartedEvent event) {
        this.client = clientLifecycle.get();
        // do something using the client
    }
```

This bean is provides common functionality and I use Spring Boot autoconfiguration to initalize it.

I wrote a Spring Boot integration test to check a class based on the bean but it fails because the `ClientStartedEvent` event is [never fired in a test](https://github.com/camunda-community-hub/spring-zeebe/blob/master/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/lifecycle/ZeebeClientLifecycle.java#L44).

As a workaround I tried to send the event manually:

```java
    @Autowired
    private ZeebeClient client;
    
    @BeforeEach
    public void wireBpmn() {
        if (wired) {
            return;
        }
        publisher.publishEvent(new ClientStartedEvent());
        wired = true;
    }
```

But even this fails with:
```
java.lang.IllegalStateException: ZeebeClient is not yet created!
	at io.camunda.zeebe.spring.client.lifecycle.ZeebeClientLifecycle.get(ZeebeClientLifecycle.java:73)
```

Third approach was to use `implements Consumer<ZeebeClient>` instead but this is also not called. The bean I want to test works great in a "normal" Spring Boot environment. `ZeebeClientLifecycle` as well as `Consumer<ZeebeClient>` are called to handover the client created and connected.

I tried to figure out the root-cause but didn't get it. The `ZeebeClient` is created and available in the test but not connected to the `ZeebeClientLifecycle`. Why is all this treated different in case of a Spring Boot test? Is there any other workaround I can get my tests running?

Thx, Stephan

**Comment by berndruecker** [comment]
Hi @stephanpelikan - do you have some concrete code to share where I could have a look? I am especially interested why you want to listen to the event.

And actually I just cleaned up the whole lifecycle a little bit (context https://github.com/camunda-community-hub/spring-zeebe/issues/275), see https://github.com/camunda-community-hub/spring-zeebe/pull/353 - how does your problem look in that context? Maybe you could try with that branch?

In general, test cases start their own engine once per test method - that's why there is a different lifecycle to a production application - that just has one overall lifecycle (the Spring Boot app)

**Comment by stephanpelikan** [comment]
Hi @berndruecker, as you know we introduced a [Camunda Community Extension](https://github.com/camunda-community-hub/vanillabp-camunda8-adapter) as an abstraction layer as suggested in [migration guide](https://docs.camunda.io/docs/guides/migrating-from-camunda-platform-7/#prepare-for-smooth-migrations). It deployes the BPMN & DMN files found in classpath once Zeebe is available and starts job-workers for each wired task. This is done based on `ClientStartedEvent`.

I want to add integration tests which test several use cases covered by our extension. Therefore I need the event to fire. So, I want to develop a common Spring Boot based test using the Zeebe test-engine instead of an external Zeebe. Doing Zeebe-assertions is only a nice-to-have because I can test the outcome of a test also by other aspects than Zeebe.

Maybe I need to do it in [the way the official Zeebe Spring client does](https://github.com/camunda-community-hub/spring-zeebe/blob/main/test/embedded/src/main/java/io/camunda/zeebe/spring/test/ZeebeTestExecutionListener.java) instead of using Zeebe-test library.

Regarding #275:
- As I saw ClientStartedEvent [is now deprecated](https://github.com/camunda-community-hub/spring-zeebe/pull/353/files#diff-e015184635557dff104b499e062195cec7d1a8217cb175aa5a0e5b59f9b754a1R3). Do I just need to inject ZeebeClient and it will already be connected? Will the Spring Boot container fail to start if connection cannot be established?
- I can give it a try within the next days and give you feedback and also a link to the test-code.

**Comment by berndruecker** [comment]
Quick comments:

- The `ClientStartedEvent` was not really doing what it was named, so I deprecated it now.
- But you can look at this bean, that does start the workers after the client is created: https://github.com/camunda-community-hub/spring-zeebe/blob/auto-configuration/client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/lifecycle/ZeebeAnnotationLifecycle.java. This does work soley because the ZeebeClient is a dependency and need to be constructed first
- Which is done here now: https://github.com/camunda-community-hub/spring-zeebe/blob/auto-configuration/client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/ZeebeClientConfiguration.java#L30 - no proxy or nothing. 
- Creating the client does NOT fail if you don't use it 

So in summary: Yes - you should be good just autowiring the ZeebeClient.

This should also automatically in test cases that use @ZeebeSpringTest - as the ZeebeClient is provided there as well - but differently: https://github.com/camunda-community-hub/spring-zeebe/blob/auto-configuration/test/common/src/main/java/io/camunda/zeebe/spring/test/proxy/TestProxyConfiguration.java#L38

But yes - you have to make sure to deploy / start workers properly for every test case. Thinking about it - that might actually be nice to hide behind events - than this line (https://github.com/camunda-community-hub/spring-zeebe/blob/auto-configuration/test/common/src/main/java/io/camunda/zeebe/spring/test/AbstractZeebeTestExecutionListener.java#L45) might simply also throw the right event and the general lifecycle would base on the events.

I actually like this thought and think, that could further cleanup things - let me have another look at it (not sure if I will make it today though).

**Comment by berndruecker** [comment]
Switched to events now: https://github.com/camunda-community-hub/spring-zeebe/commit/c8a8b052583ee5f8b68a7c731fdc44735ab10008 - @stephanpelikan you should be able to leverage those for your own deployments in the abstraction layer - prod as test - should both work. Let me know if that fix things for you - and thanks for the nudge :-)

**Comment by berndruecker** [comment]
I merged the PR, so you can try with the latest SNAPSHOT from main. I will close this issue for housekeeping - but feel free to reopen if that does not work as expected @stephanpelikan !
