### ISSUE TITLE
Parsing of variables with generic types to a wrong type

### ISSUE THREAD

**Issue by vat78** [camunda-community-hub/spring-zeebe#327]
I've faced with an exception that surprised me.
This is an example of the worker:

```
    @JobWorker(type = "processTasks")
    public void processTasks(@Variable List<Long> batch) {
        var firstElement = batch.get(0);
    }
```
And it fails in runtime with java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long 

Input list comes as `List<Integer>` in runtime and can't be matched to firstElement with type Long

**Comment by berndruecker** [comment]
This is because the data is serialized as JSON and deserialized later, and then Jackson guesses the type depending on size (see related https://github.com/FasterXML/jackson-databind/issues/504).

In general, using Type references (https://javadoc.io/static/com.fasterxml.jackson.core/jackson-core/2.12.1/com/fasterxml/jackson/core/type/TypeReference.html) or probably some annotations might also help - but this would need to be buried quite deep in the Java Client, which is probably not easy to do right. But happy to take a PR :-)

Maybe `List<Number>` is the easiest option @vat78 ?

**Comment by jonathanlukas** [comment]
I would wrap the whole variable context and provide it as @VariablesAsType:
```
public record BatchVariables(List<Long> batch) {}
```
That would work
