### ISSUE TITLE
Executor Service doesn't respect configured worker's thread-pool-size

### ISSUE THREAD

**Issue by shahabio** [camunda-community-hub/spring-zeebe#424]
When we configured 'zeebe.worker.threads' size in the application.properties, based on the auto configurations, won't affect the actual worker's thread pool size.

Based on this `@Conditional` bean, it needs Spring Actuator which uses Micrometer to be on the classpath to auto-configure a threads size and uses the passed configuration from application.properties:

```java
import io.micrometer.core.instrument.MeterRegistry;

@ConditionalOnClass(MeterRegistry.class) // micrometer needs to be on the classpath
@ConditionalOnMissingBean(ZeebeClientExecutorService.class)
public class ExecutorServiceConfiguration {
``` 

Otherwise, ZeebeClientExecutorService will configure a Single Thread Pool size for the workers:

```java
  public static ZeebeClientExecutorService createDefault() {
    ScheduledExecutorService threadPool = Executors.newSingleThreadScheduledExecutor(); // configure a default single thread pool
    return new ZeebeClientExecutorService(threadPool);
  }
```

Spring-zeebe: 8.2.0
Spring boot: 3.0.6
Java: 17

Regards.
Shahab.

**Comment by shahamit** [comment]
We have the micrometer library in our classpath but still setting the`zeebe.client.worker.threads` doesn't have any effect. On enabling trace logs, I could see that the job poller doesn't poll for the job worker until the currently executing task is completed. 

This is a blocker for parallel execution of tasks. Can it be prioritised and looked into? @berndruecker

**Comment by berndruecker** [comment]
@1nb0und?

**Comment by 1nb0und** [comment]
@shahamit This will be prioritized for the next release

**Comment by shahamit** [comment]
@1nb0und - would this be a fix in this repo? On debugging the source I realised that we need to register multiple job workers for every job type then only increasing the worker threads takes into effect. Probably that's because there is a job poller per job worker (instead of being at the zeeclient level). I just raised [this issue](https://github.com/camunda/zeebe/issues/14662) under this assumption. What are your thoughts?

**Comment by 1nb0und** [comment]
@shahamit I investigated on my end and tested either 8.2.4 or 8.3.0 and I can see the parallelism working by setting `zeebe.client.worker.threads` 

Logs:
```
2023-10-16T22:19:13.790-04:00  INFO 26443 --- [           main] i.c.z.spring.example.ExampleApplication  : Started ExampleApplication in 1.08 seconds (process running for 1.291)
2023-10-16T22:19:19.570-04:00 DEBUG 26443 --- [ault-executor-1] io.camunda.zeebe.client.job.poller       : Activated 1 jobs for worker exampleJobWorkers#handleFooJob and job type foo
2023-10-16T22:19:19.571-04:00  INFO 26443 --- [pool-2-thread-3] i.c.z.spring.example.ExampleJobWorkers   : complete job
2023-10-16T22:19:29.652-04:00 DEBUG 26443 --- [ault-executor-3] io.camunda.zeebe.client.job.poller       : Activated 4 jobs for worker exampleJobWorkers#handleFooJob and job type foo
2023-10-16T22:19:29.652-04:00  INFO 26443 --- [pool-2-thread-1] i.c.z.spring.example.ExampleJobWorkers   : complete job
2023-10-16T22:19:29.652-04:00  INFO 26443 --- [pool-2-thread-5] i.c.z.spring.example.ExampleJobWorkers   : complete job
2023-10-16T22:19:29.652-04:00  INFO 26443 --- [pool-2-thread-2] i.c.z.spring.example.ExampleJobWorkers   : complete job
2023-10-16T22:19:29.652-04:00  INFO 26443 --- [pool-2-thread-4] i.c.z.spring.example.ExampleJobWorkers   : complete job
```


One reason why parallelism won't work is it doesn't find the `micrometer` library on the class path (I know you mentioned its included already). Would you mind to provide some startup logs that shows the `micrometer` library has been loaded? You can paste it below.

It should look like the following

```
2023-10-16 22:28:48.976  INFO 27073 --- [           main] i.c.z.s.c.a.MicrometerMetricsRecorder    : Enabling Micrometer based metrics for spring-zeebe (available via Actuator)
```

On a side note, a good follow-up improvement would be to decouple the dependency of setting custom executor / parallel threads with micrometer. Need to revisit why those 2 have to be coupled with each other.

**Comment by shahamit** [comment]
@1nb0und - Appreciate your efforts in reproducing the issue. Reproducing the test would need sometime but from the logs you shared above, I can notice that job poller "activates" the job only if the previous one completes.

In my tests I had observed that if we have a job that takes few secs or a min, no polling (i.e. no logs from job poller) happens during that period. Only after a job completes, the job poller polls for jobs and activates them. 

This happens when there is only one worker. As a workaround we have increased the number of job workers registered for a particular job type. 

Can you please increase the job execution time and re-run your tests?

Also this behaviour was observed by @nthed on [this](https://github.com/camunda/zeebe/issues/14662#issuecomment-1761368077) bug report too. 

Will look forward for your observations.

**Comment by micudaj** [comment]
when I set zeebe.client.worker.threads to a higher number I have the problem that the first process instance works fine but the following process instances I start while the first one is still busy fail with the error "Error during json mapping". Any idea what might be the issue here?
