### ISSUE TITLE
neither zeebe.client.connection-mode nor zeebe.client.connectionMode work

### ISSUE THREAD

**Issue by marcosdiez** [camunda-community-hub/spring-zeebe#450]
Hi,

we have some envs using SaaS and some self hosted.
We learned in the worst possible way that 
* the documentation is wrong, here is the fix: https://github.com/camunda-community-hub/spring-zeebe/pull/449
* neither `zeebe.client.connection-mode` nor `zeebe.client.connectionMode` work

The workaround is from a far sight, simple, one just needs to use the following settings:

```
zeebe.client.broker.gatewayAddress=127.0.0.1:26500
zeebe.client.security.plaintext=true
```

and no other.

But actually that causes a problem in our CI/CD pipeline, because now we can't have the same settings file for both.

This is extremely confusing and debugging that was not fun.

**Comment by ness-IgorsShestiperov** [comment]
Just to add here. 

Error happens in ZeebeClientConfigurationProperties class: 

`  @Override
  public CredentialsProvider getCredentialsProvider() {
    if (cloud.clientId != null && cloud.clientSecret != null) {
//        log.debug("Client ID and secret are configured. Creating OAuthCredientialsProvider with: {}", this);
      return CredentialsProvider.newCredentialsProviderBuilder()
        .clientId(cloud.clientId)
        .clientSecret(cloud.clientSecret)
        .audience(cloud.getAudience())
        .authorizationServerUrl(cloud.authUrl)
        .credentialsCachePath(cloud.credentialsCachePath)
        .build();
    }
    return null;
  }`

It doesn't take into account connection mode property at all. If both configs are set to something it will fail.

**Comment by mkresse** [comment]
We have a similar issue: multiple environments use a common configuration using oauth via `zeebe.client.cloud` property. For local execution however we just use cookie based authentication. Due to [this issue](https://github.com/spring-projects/spring-framework/issues/19986) it's not possible to overwrite any property with `null`, so we need to create many equal configuration files for each environment. I would propose to change the  aforementioned responsible condition from `cloud.clientId != null` to `hasText(cloud.clientId)`, since it does not seem to maky any sense to define a clientId (or secret) with an empty string. I'll try to prepare a PR for this.
