### ISSUE TITLE
'ProcessInstanceEvent' join() didn't work

### ISSUE THREAD

**Issue by wanhanbo** [camunda-community-hub/spring-zeebe#460]
I used SpringBoot 2.7.6 and JDK11, spring-zeebe.version==8.2.4
I wanna trigger the scheduled task `startProcess` in which I depoly a new process and start it. And I wish the `processInstanceEvent` used `xxxx.send().join()` can block here until the jobworkers completes so that the next scheduled task can't start.
However, the next scheduled task still started before the jobworker completes. I make sure the @Scheduled is a single-thread task so the problem may be that the `join()` didn't work. In fact, even if I don't use the scheduled task, but use a controller to trigger the `startprocess` multiple times, the same thing will happen.
Maybe my understanding of `join()` is wrong, please give me some help, thank you~~

```
   @Scheduled(fixedDelay = 30*1000L)
    public String startProcess(){
        count.incrementAndGet();
        logger.info("Process times: {}",count);

        //Deploy a new process
        DeploymentEvent deploymentEvent =
                client.newDeployResourceCommand()
                        .addResourceFromClasspath("model/apolloTest.bpmn")
                        .send()
                        .join();
        Map<String, Object> variables = new HashMap<String, Object>(){{
            put("isEnd",false);
        }};
        //start the process
        ProcessInstanceEvent processInstanceEvent = client
                .newCreateInstanceCommand()
                //.processDefinitionKey(deploymentEvent.getKey())
                .bpmnProcessId(deploymentEvent.getProcesses().get(0).getBpmnProcessId())
                .latestVersion()
                .variables(variables)
                .send()
                .join();
        // I wanna block here until the jobworker completes
        return new Date().toString();
    }
```

**Comment by GregDThomas** [comment]
I think (but new here, so may be wrong) that you understanding is wrong. The join() merely waits until the process has started. You can then use the process instance key to monitor the state of that process (which may not finish for days, weeks, etc.)

**Comment by berndruecker** [comment]
Hi @wanhanbo: Your understanding of join is not correct. It blocks until the starting of the process instance has been completed, but not until the process advances or complete jobs.

You could use "withResult" if you want to block until the process instance completes (see https://docs.camunda.io/docs/next/apis-tools/grpc/#createprocessinstancewithresult-rpc). 

If you need for a specific job worker to complete, you might need a separate service task with a job type defined by a unique UUID, and then you can start a job worker just for this in your current thread, so that you will get notified if your process is in this state. Not that this can influence scaling behavior if you are in a high load scenario.

Hope that helps!
